### ISSUE TITLE
core dump and logs are copied from a .bz2 to a .tgz file

### ISSUE THREAD

**Issue by mykaul** [gluster/glusterfs-patch-acceptance-tests#194]
In https://github.com/gluster/glusterfs-patch-acceptance-tests/blob/6966df54ca1673a46b58ca19ba61925da7492c7e/regression.sh#L169 we actually copy a .bz2 compressed file and call it a .tgz file. This is incorrect - the file is still .bz2.

**Comment by sankarshanmukhopadhyay** [comment]
@deepshikhaaa do we need the .tgz for specific reasons?

**Comment by deepshikhaaa** [comment]
Thanks, Yaniv for pointing this out. I don't recall why we did this store tar files this way. But yes let's see if something changes on this update.
