### ISSUE TITLE
Duplication of scripts used by the centos-ci

### ISSUE THREAD

**Issue by nixpanic** [gluster/glusterfs-patch-acceptance-tests#81]
It seems that #80 did not address the issue it was trying to. There are copies of the different scripts under the `centos-ci/scripts` directory. The version of `build.sh` was not modified there. Please remove the copies of the scripts (optionally symlink them) and make sure there is only one version of them.

Thanks!

**Comment by nigelbabu** [comment]
What do you mean by copies of build.sh? The scripts in `scripts` folder are the ones consumed by JJB. As far as I know, there are no copies of that script. The other folders remain untouched pending a convert to JJB. Not sure what you're trying to do?

**Comment by nixpanic** [comment]
In PR #80 I attempted to get more verbose output from the `mock` command
that is used for the nightly builds in the CentOS CI. That change got
merged, but the output is not more verbose than before.

It was my assumption that the `nightly-builds/build.sh` script was used,
but after browsing this repository, I found a copy of the script in the
`scripts/` directory.

If the `scripts/build.sh` is not used by the CentOS CI for nightly
builds, do you have an idea why PR #80 did not result in a more verbose
output?

Thanks!

**Comment by nigelbabu** [comment]
Ah, so PR #80 was trying to change a redundant script. I've deleted all the scripts that are not actively used to avoid confusion.
