### ISSUE TITLE
update-issue.py has a too strict regex that may cause smoke tests to fail

### ISSUE THREAD

**Issue by nixpanic** [gluster/glusterfs-patch-acceptance-tests#84]
[A change](https://review.gluster.org/#/c/17194/1) that has a commit message with the word "fixes" at the start of a sentence may cause a Python exception when `update-issue.py` is executed:

```
[comment-on-issue] $ /bin/sh -xe /tmp/hudson3968632679950173606.sh
+ /opt/qa/update-issue.py
Traceback (most recent call last):
  File "/opt/qa/update-issue.py", line 103, in <module>
    main(args.dry_run, args.force)
  File "/opt/qa/update-issue.py", line 85, in main
    issues = parse_commit_message(commit)
  File "/opt/qa/update-issue.py", line 43, in parse_commit_message
    bugs.append(regex.match(line).group(5))
AttributeError: 'NoneType' object has no attribute 'group'
Build step 'Execute shell' marked build as failure
Finished: FAILURE
```

Because this is a step in the smoke regression testing, the smoke test is marked as a failure.

CC: @ShyamsundarR @soumyakoduri

**Comment by nigelbabu** [comment]
https://github.com/gluster/glusterfs-patch-acceptance-tests/commit/027b88ed94cb3cc397b49b03e7d52280602e344f
